# Generated by Django 3.1.5 on 2021-01-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='email',
            field=models.CharField(default='', max_length=250),
        ),
    ]
