# Generated by Django 3.1.5 on 2021-01-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='email',
            field=models.EmailField(default='', max_length=250),
        ),
    ]
